#!/usr/bin/env node
/**
 * POLYTRACK — Setup Script
 * Run: node setup.js
 * Guides you through configuration and starts the server
 */

import { createInterface } from "readline";
import { writeFileSync, existsSync, readFileSync } from "fs";
import { execSync } from "child_process";

const rl = createInterface({ input: process.stdin, output: process.stdout });
const ask = (q) => new Promise(r => rl.question(q, r));

const GREEN  = s => `\x1b[32m${s}\x1b[0m`;
const YELLOW = s => `\x1b[33m${s}\x1b[0m`;
const CYAN   = s => `\x1b[36m${s}\x1b[0m`;
const BOLD   = s => `\x1b[1m${s}\x1b[0m`;
const DIM    = s => `\x1b[2m${s}\x1b[0m`;

console.clear();
console.log(BOLD(GREEN(`
╔═══════════════════════════════════════════════════╗
║          POLYTRACK — Setup Wizard                 ║
║   Smart Wallet Tracker & Auto-Copy Trading Bot    ║
╚═══════════════════════════════════════════════════╝
`)));

async function main() {
  // Check if .env already exists
  if (existsSync(".env")) {
    const overwrite = await ask(YELLOW("⚠  .env already exists. Overwrite? (y/N): "));
    if (overwrite.toLowerCase() !== "y") {
      console.log(GREEN("\nKeeping existing .env. Starting server…\n"));
      rl.close();
      startServer();
      return;
    }
  }

  console.log(CYAN(`
This wizard will configure your POLYTRACK backend.
Press ENTER to skip any field (read-only mode, no real trades).
`));

  // ── Read-only or trading mode?
  const mode = await ask(BOLD("Mode? [1] Read-only (no trading)  [2] Auto-copy trading (1/2): "));
  const trading = mode.trim() === "2";

  let privateKey = "", funderAddress = "", apiKey = "", apiSecret = "", passphrase = "";
  let watchWallets = "";

  if (trading) {
    console.log(YELLOW(`
⚠  TRADING MODE — Real USDC will be spent.
   Make sure your wallet has USDC on Polygon and allowances are set.
   See: https://github.com/Polymarket/py-clob-client#allowances
`));
    privateKey    = (await ask("  Private key (0x…, hidden): ")).trim();
    funderAddress = (await ask("  Funder/proxy wallet address (0x…): ")).trim();
    apiKey        = (await ask("  Polymarket API key (optional): ")).trim();
    apiSecret     = (await ask("  Polymarket API secret (optional): ")).trim();
    passphrase    = (await ask("  Polymarket API passphrase (optional): ")).trim();
  }

  // ── Trading settings
  const maxTrade   = (await ask(DIM(`Max USDC per auto-trade [100]: `))).trim() || "100";
  const minWallets = (await ask(DIM(`Min ELITE wallets for signal [3]: `))).trim() || "3";
  const scanInt    = (await ask(DIM(`Scan interval in seconds [60]: `))).trim() || "60";
  watchWallets     = (await ask(DIM("Extra wallets to watch (comma-separated, optional): "))).trim();

  // ── Write .env
  const envContent = `# POLYTRACK — generated by setup.js
PORT=3001

# Trading wallet
PRIVATE_KEY=${privateKey}
FUNDER_ADDRESS=${funderAddress}

# Polymarket API credentials
POLY_API_KEY=${apiKey}
POLY_API_SECRET=${apiSecret}
POLY_PASSPHRASE=${passphrase}

# Auto-copy settings
MAX_TRADE_USDC=${maxTrade}
MIN_WALLETS=${minWallets}
SCAN_INTERVAL=${scanInt}
WATCH_WALLETS=${watchWallets}
`;

  writeFileSync(".env", envContent);
  console.log(GREEN("\n✓ .env saved\n"));

  // ── Install dependencies
  console.log(CYAN("Installing dependencies…"));
  try {
    execSync("npm install", { stdio: "inherit" });
    console.log(GREEN("✓ Dependencies installed\n"));
  } catch (e) {
    console.log(YELLOW("⚠  npm install failed — try running manually: npm install\n"));
  }

  rl.close();

  console.log(BOLD(GREEN(`
╔═══════════════════════════════════════════════════╗
║                  Setup complete!                  ║
╚═══════════════════════════════════════════════════╝
`)));
  console.log(`  Mode:         ${trading ? GREEN("AUTO-COPY TRADING") : YELLOW("READ-ONLY")}`);
  console.log(`  Max trade:    ${GREEN("$" + maxTrade + " USDC")}`);
  console.log(`  Threshold:    ${GREEN(minWallets + "+ ELITE wallets")}`);
  console.log(`  Scan every:   ${GREEN(scanInt + "s")}`);
  console.log(`\n  Server URL:   ${CYAN("http://localhost:3001")}`);
  console.log(`  Health check: ${CYAN("http://localhost:3001/health")}\n`);

  console.log(CYAN("Frontend setup:"));
  console.log(`  1. Add ${BOLD("socket.io-client")} to your React app: ${DIM("npm install socket.io-client")}`);
  console.log(`  2. Import ${BOLD("App.jsx")} from the ${BOLD("frontend/")} folder`);
  console.log(`  3. Make sure SERVER in App.jsx points to ${BOLD("http://localhost:3001")}\n`);

  const start = await ask(BOLD("Start the server now? (Y/n): "));
  if (start.toLowerCase() !== "n") {
    startServer();
  }
}

function startServer() {
  console.log(GREEN("\n🚀 Starting POLYTRACK server…\n"));
  const { spawn } = await import("child_process").catch(() => require("child_process"));
  const proc = spawn("node", ["server.js"], { stdio: "inherit" });
  proc.on("exit", code => process.exit(code));
}

main().catch(e => { console.error(e); process.exit(1); });
